In [2]:
import numpy  as np
import pandas as pd
from sklearn import tree
from sklearn.cluster import KMeans


In [33]:
csv = pd.read_csv('CASAS.csv')
df_living = pd.read_csv('CASAS.csv', usecols=['sqft_living'])
df_lot = pd.read_csv('CASAS.csv', usecols=['sqft_lot'])
df_above = pd.read_csv('CASAS.csv', usecols=['sqft_above'])
df_basement = pd.read_csv('CASAS.csv', usecols=['sqft_basement'])

In [34]:
X_living = np.array(df_living)
X_lot = np.array(df_lot)
X_above = np.array(df_above)
X_basement = np.array(df_basement)

In [36]:
X_lot

array([[ 10000],
       [ 19901],
       [ 10002],
       [ 26300],
       [ 13959],
       [ 10000],
       [  9263],
       [  5802],
       [  8280],
       [  5493],
       [ 15842],
       [ 11575],
       [  6750],
       [  4912],
       [ 23899],
       [ 12940],
       [ 18600],
       [  6172],
       [  4862],
       [ 12240],
       [ 10450],
       [ 28405],
       [ 36831],
       [  6195],
       [ 11287],
       [ 17239],
       [ 10350],
       [ 12473],
       [  9153],
       [  7920],
       [ 12987],
       [ 12682],
       [ 13113],
       [ 11457],
       [  6413],
       [ 13058],
       [  9670],
       [ 12350],
       [ 10454],
       [ 11200],
       [  7684],
       [  9993],
       [ 10000],
       [  9998],
       [  9676],
       [ 11393],
       [ 11562],
       [  9780],
       [  9984],
       [  9903],
       [ 10513],
       [ 10031],
       [  8392],
       [ 14100],
       [  9225],
       [ 12253],
       [  5737],
       [ 11934],
       [117612

In [38]:
k_living = KMeans(n_clusters=3, random_state=0)
k_lot = KMeans(n_clusters=3, random_state=0)
k_above = KMeans(n_clusters=3, random_state=0)
k_basement = KMeans(n_clusters=3, random_state=0)

In [39]:
k_living.fit(X_living)
k_lot.fit(X_lot)
k_above.fit(X_above)
k_basement.fit(X_basement)

KMeans(n_clusters=3, random_state=0)

In [30]:
k_above.labels_

array([0, 0, 0, 1, 2, 0, 0, 1, 0, 2, 1, 2, 2, 2, 2, 2, 1, 1, 1, 0, 0, 1,
       0, 0, 2, 2, 0, 0, 2, 2, 0, 1, 2, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 1, 0, 2, 0, 0, 0, 2, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 2, 2, 0,
       0, 2, 2, 2, 1, 0, 0, 2, 2, 0, 2, 0, 0, 0, 0, 0, 2, 0, 2, 2, 0, 0,
       2, 2, 0, 0, 0, 0, 0, 0, 0, 2, 2, 0, 0, 2, 2, 0, 2, 0, 0, 1, 0, 0,
       2, 2, 2, 0, 2, 2, 0, 2, 0, 2, 1, 1, 0, 2, 0, 0, 2, 0, 1, 1, 1, 0,
       2, 2, 2, 0, 2, 0, 2, 0, 2, 2, 1, 2, 0, 0, 1, 0, 2, 0, 0, 2, 0, 1,
       0, 0, 2, 2, 0, 0, 2, 2, 1, 2, 0, 1, 0, 0, 0, 1, 1, 0, 1, 2, 2, 0,
       2, 2, 0, 0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 2, 2, 0, 1, 0, 0, 1, 0, 1,
       0, 1, 0, 2, 2, 0, 1, 2, 0, 2, 1, 0, 0, 2, 1, 0, 0, 2, 0, 0, 2, 1,
       2, 0, 0, 0, 0, 2, 0, 2, 0, 0, 0, 0, 2, 0, 2, 0, 0, 0, 1, 1, 0, 2,
       0, 0, 2, 2, 2, 2, 0, 2, 0, 0, 2, 1, 1, 2, 0, 1, 1, 1, 1, 2, 1, 1,
       0, 0, 1, 0, 1, 1, 1, 1, 2, 1])

In [29]:
k_living.labels_

array([2, 2, 0, 1, 0, 2, 0, 1, 2, 0, 1, 0, 1, 0, 0, 2, 0, 0, 0, 2, 0, 0,
       2, 2, 1, 0, 2, 0, 0, 1, 0, 1, 1, 2, 0, 1, 2, 0, 0, 0, 0, 2, 0, 2,
       0, 1, 0, 2, 0, 2, 2, 2, 2, 0, 0, 1, 0, 2, 1, 2, 0, 1, 1, 1, 0, 0,
       2, 0, 0, 0, 0, 2, 2, 0, 0, 2, 0, 2, 2, 2, 2, 2, 0, 2, 0, 0, 0, 0,
       0, 2, 0, 0, 2, 0, 1, 0, 0, 2, 0, 2, 0, 2, 0, 2, 0, 0, 0, 0, 2, 0,
       1, 0, 2, 2, 0, 2, 2, 0, 2, 1, 1, 1, 0, 2, 2, 1, 0, 2, 0, 0, 1, 2,
       0, 0, 0, 0, 0, 2, 1, 2, 0, 0, 1, 0, 2, 2, 1, 0, 0, 0, 0, 0, 2, 0,
       0, 2, 2, 0, 2, 2, 0, 0, 0, 1, 2, 1, 2, 2, 2, 0, 1, 2, 1, 0, 2, 2,
       0, 0, 2, 1, 2, 2, 0, 2, 2, 2, 0, 0, 0, 0, 0, 2, 1, 2, 0, 0, 0, 1,
       0, 1, 2, 0, 2, 2, 0, 0, 2, 1, 0, 2, 2, 1, 1, 2, 2, 0, 0, 0, 0, 0,
       0, 2, 0, 2, 2, 0, 2, 0, 2, 0, 0, 2, 0, 0, 2, 2, 0, 2, 0, 0, 0, 0,
       2, 0, 0, 0, 0, 1, 0, 1, 2, 0, 0, 1, 1, 0, 2, 1, 1, 1, 0, 0, 1, 1,
       2, 0, 0, 2, 1, 1, 0, 1, 0, 0])

In [40]:
csv['K-sqft_living'] = k_living.labels_
csv['K-sqft_lot'] = k_lot.labels_
csv['K-sqft_above'] = k_above.labels_
csv['K-sqft_basement'] = k_basement.labels_

In [41]:
print(csv)

     bedrooms  bathrooms  sqft_living  sqft_lot  floors  waterfront  view  \
0           2       1.00          770     10000     1.0           0     0   
1           3       1.00         1430     19901     1.5           0     0   
2           4       2.25         2590     10002     1.0           0     0   
3           4       2.75         3820     26300     2.0           0     0   
4           3       3.00         2420     13959     1.0           0     0   
..        ...        ...          ...       ...     ...         ...   ...   
269         4       2.50         2840      4500     2.0           0     0   
270         4       2.75         2630      4501     2.0           0     0   
271         4       2.75         2990      4521     2.0           0     0   
272         4       3.00         2290      5105     2.0           0     0   
273         4       2.50         2470      7539     2.0           0     0   

     condition  sqft_above  sqft_basement  K-sqft_living  K-sqft_lot  \
0  

In [42]:
csv.to_csv("C:\\Users\\T-Gamer\\KMEDIAS\\testekmed.csv")